<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<!-- Target framework and WinForms -->
		<TargetFrameworks>net10.0-windows;net8.0-windows;net6.0-windows</TargetFrameworks>
		<LangVersion>10.0</LangVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- NuGet metadata -->
		<PackageId>Leekz.CodeTextBox</PackageId>
		<Version>1.0.1</Version>
		<Authors>PIN0L33KZ</Authors>
		<Company>PIN0L33KZ GbR</Company>
		<Product>LeekzCodeTextBox</Product>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<Description>WinForms code editor control with line numbers, zoom and change markers.</Description>
		<PackageTags>winforms;editor;code;text;linenumbers;textbox;leekz;l33kz;pinoleekz;pin0l33kz</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!-- Optional but nice -->
		<PackageProjectUrl>https://www.pinoleekz.de</PackageProjectUrl>
		<RepositoryUrl>https://github.com/PIN0L33KZ/LeekzCodeTextBox</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- Build will automatically create a .nupkg -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<!-- Keine Lizenzabfrage im NuGet-Dialog -->
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<!-- README in das Paket einpacken, im Root des .nupkg -->
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>